/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administracion;

import Basededatos.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin_000
 */
public class SancionesJugador extends javax.swing.JPanel {

    /**
     * Creates new form AgregarSanciones
     */
    public SancionesJugador() {
        initComponents();
    }
public void HabilitarGuardar(){
        
        String Sancion=this.CampoSancion.getText();
        String Fechas=this.CampoFechas.getText();
        String Deuda=this.CampoDeuda.getText();

        
        if(Sancion.isEmpty() || Fechas.isEmpty() || Deuda.isEmpty()){
            
                this.BotonGuardar.setEnabled(false);
        }
        
        else{
            this.BotonGuardar.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        CampoSancion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoFechas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoDeuda = new javax.swing.JTextField();
        BotonLimpiar = new javax.swing.JButton();

        setOpaque(false);

        jLabel1.setText("Motivo de Sanción a Registrar:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nuevo Motivo de Sanción para Jugadores");

        BotonGuardar.setEnabled(false);
        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconosformulario/guardar30x30.png"))); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.setBorder(null);
        BotonGuardar.setBorderPainted(false);
        BotonGuardar.setContentAreaFilled(false);
        BotonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonGuardar.setIconTextGap(-2);
        BotonGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconosformulario/guardar40x40.png"))); // NOI18N
        BotonGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconossalir/exit6 30x30.png"))); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.setBorder(null);
        BotonSalir.setBorderPainted(false);
        BotonSalir.setContentAreaFilled(false);
        BotonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonSalir.setIconTextGap(-2);
        BotonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconossalir/exit6 40x40.png"))); // NOI18N
        BotonSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        CampoSancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoSancionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoSancionKeyTyped(evt);
            }
        });

        jLabel3.setText("Fechas de Suspensión:");

        CampoFechas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoFechasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoFechasKeyTyped(evt);
            }
        });

        jLabel4.setText("Monto de la Deuda:");

        CampoDeuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoDeudaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoDeudaKeyTyped(evt);
            }
        });

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconosformulario/limpiar30x30.png"))); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.setBorder(null);
        BotonLimpiar.setBorderPainted(false);
        BotonLimpiar.setContentAreaFilled(false);
        BotonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLimpiar.setIconTextGap(-2);
        BotonLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconosformulario/limpiar40x40.png"))); // NOI18N
        BotonLimpiar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoSancion)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81)))
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoSancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CampoFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
    Gadministracion.paneladministracion.remove(this);
    Gadministracion.habilitar();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
    String MotivoSancionJugadores=this.CampoSancion.getText();

    int FechasSuspension=Integer.parseInt(this.CampoFechas.getText());
    
    float MontoPagar=Float.parseFloat(this.CampoDeuda.getText());
    
        int Opcion=JOptionPane.showConfirmDialog(null,"¿Está seguro que desea registrar el motivo de sanción introducido?","Informacion",JOptionPane.YES_NO_OPTION);
        
        if(Opcion==0){
            
    
    try{        
    int Motivo=0;
    String query2="SELECT motivo_sanciones_jugadores FROM motivo_sanciones_jugadores WHERE motivo_sanciones_jugadores='"+MotivoSancionJugadores+"';";
    Conexion parametros2 = new Conexion();
    Class.forName(parametros2.getDriver());
    Connection con2=DriverManager.getConnection(parametros2.getURL(), parametros2.getUsuario(), parametros2.getPass());
    Statement st2=con2.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet rs2=st2.executeQuery(query2);
    if(rs2.first()){
        Motivo=2;  
    }
    if(Motivo==2){
         
          JOptionPane.showMessageDialog(this,"Ese Motivo de Sanción para Jugadores ya se Encuentra Registrado","Información",JOptionPane.INFORMATION_MESSAGE);
      }
    else{
        try{
     String query="INSERT INTO motivo_sanciones_jugadores VALUES('"+MotivoSancionJugadores+"','"+FechasSuspension+"','"+MontoPagar+"');";
    Conexion parametros = new Conexion();
    Class.forName(parametros.getDriver());
    Connection con=DriverManager.getConnection(parametros.getURL(), parametros.getUsuario(), parametros.getPass());
    Statement st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    st.executeUpdate(query);
    
    JOptionPane.showMessageDialog(this,"Motivo de Sanción para Jugadores Registrado Exitosamente","Información",JOptionPane.INFORMATION_MESSAGE);
    Gadministracion.habilitar();
    Gadministracion.paneladministracion.remove(this);
    
        }catch(SQLException ex){
            Logger.getLogger(SancionesJugador.class.getName()).log(Level.SEVERE,null,ex);
        }catch(ClassNotFoundException e){
            Logger.getLogger(SancionesJugador.class.getName()).log(Level.SEVERE,null,e);
        }
        
        
    }
        }catch(SQLException ex){
            Logger.getLogger(SancionesJugador.class.getName()).log(Level.SEVERE,null,ex);
        }catch(ClassNotFoundException e){
            Logger.getLogger(SancionesJugador.class.getName()).log(Level.SEVERE,null,e);
        }
        }
        
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void CampoFechasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoFechasKeyTyped
           int Limite=50;
    char K;
    K=evt.getKeyChar();
    if (CampoFechas.getText().length()== Limite){
     evt.consume();
    }
    if(K<'0'|| K>'9'){
     evt.consume();
    }
    }//GEN-LAST:event_CampoFechasKeyTyped

    private void CampoDeudaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoDeudaKeyTyped
            int Limite=50;
    char K;
    K=evt.getKeyChar();
    if (CampoDeuda.getText().length()== Limite){
     evt.consume();
    }
    if(K<'0'|| K>'9'){
     evt.consume();
    }
    }//GEN-LAST:event_CampoDeudaKeyTyped

    private void CampoSancionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoSancionKeyTyped
                     int Limite=50;
    char K;
    K=evt.getKeyChar();
    if (CampoSancion.getText().length()== Limite){
     evt.consume();
    }
    if(!(K<'0'|| K>'9')){
     evt.consume();
    }
    }//GEN-LAST:event_CampoSancionKeyTyped

    private void CampoSancionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoSancionKeyReleased
        this.HabilitarGuardar();
    }//GEN-LAST:event_CampoSancionKeyReleased

    private void CampoFechasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoFechasKeyReleased
        this.HabilitarGuardar();
    }//GEN-LAST:event_CampoFechasKeyReleased

    private void CampoDeudaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoDeudaKeyReleased
        this.HabilitarGuardar();
    }//GEN-LAST:event_CampoDeudaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField CampoDeuda;
    private javax.swing.JTextField CampoFechas;
    private javax.swing.JTextField CampoSancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
